### ISSUE TITLE
Can't get the link

### ISSUE THREAD

**Issue by sim2511** [Kosert/YoutubeDownloader#1]
Hello,

Thanks for this awesome project, I would like to know why the download link button stay grey when I put the link.

Regards,

**Comment by sim2511** [comment]
I think there is a script missing in the index.html?

**Comment by Kosert** [comment]
Hi, 

I have updated the readme file, hope that clarifies things.

**Comment by sim2511** [comment]
Hi Kosert, just wanted to know what I have to install exactly ? 

I'm on Debian 9, I have installed Nginx, PHP7 and Phpmyadmin. I'm not behind a reverse proxy, so I took Develop Branch. The "get link" button is still grey, I missed something. Regards

**Comment by Kosert** [comment]
This project is obviously not written in PHP (lol) but in node.js. You need to install nodejs and npm. Navigate to directory with `package.json` and run `npm install` to install dependencies.
Now you can run the app with `node main.js`.

**Comment by sim2511** [comment]
Thanks a lot, I have done that this morning, On the server side I correctly see app running with "server start on 2137" When I try to download I have can see the loading button, but it freeze on this loading button :/ I hope it does not from my vps

**Comment by sim2511** [comment]
can you tell me if this is correct for the reverse proxy, i'm sorry for my stupid question, but I want to learn ^_^ : 
server{
	listen 80;
	location /youtube {
	proxy_pass "htpp://127.0.0.1:2137"
	}
}
