### ISSUE TITLE
Reverse Proxy

### ISSUE THREAD

**Issue by sim2511** [Kosert/YoutubeDownloader#2]
Hello Kosert,

Could you please tell me how the reverse proxy works or share your conf file ? I'm still working on this project for many days now. I tryed many different things. 

Here my result : http://54.37.153.5/youtube/
I ran main.js, and can see server started on 2137

Sorry to disturb you, I wish I can success, best regards,

**Comment by Kosert** [comment]
If anyone is still interested, the "reverse proxy problem" is gone now.
